import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '../libs/provider/ChakraProvider'
import { AuthContextProvider } from '@/libs/provider/authContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '情報工学先生',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body>
          <AuthContextProvider>
            <Providers>
              {children}
            </Providers>
          </AuthContextProvider>
        </body>
      </html>
  )
}
