import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import HeaderTop from "../../components/Top/HeaderTop";
import FooterTop from "../../components/Top/FooterTop";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "情報工学先生Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <body
          className={`${inter.className} flex flex-col justify-between min-h-screen`}
        >
          <ThemeProvider>
            <HeaderTop />
            <main className="container mx-auto max-w-6xl">{children}</main>
            <FooterTop />
          </ThemeProvider>
        </body>
      </html>
  );
}
