import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../ui/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '情報工学先生Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col justify-between min-h-screen`}>
        <main className="container max-w-6xl">{children}</main>
      </body>
    </html>
  )
}