name: Test E2E

on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: npx playwright install
        run: npx playwright install
      - name: Run E2E Test
        run: npx playwright test